# MATH 300: Numerical Analysis I Recitation

## Instructor: Liam Doherty

## Meeting Time/Place: F 11:00AM, Curtis 453

## Office Hours: MRC Hours MR 5p-7p, W 12p-2p, or in Korman 282 by appointment

Starting with attendance...

Download & Set Up Julia/VS Code

Julia: https://julialang.org/downloads/

VS Code: https://code.visualstudio.com/Download

Install Julia VS Code extension

REPL Intro - Package Manager, basic commands & shell access

Jupyter notebooks:

In [ ]:
using Pkg; Pkg.add("IJulia")
Pkg.build("IJulia")

Now for some basic Julia programming:

If you try to use a package that does not exist on your machine (e.g., you spelled the name incorrectly **or** you have not installed it yet), you will get an error: 

In [1]:
using SomePackage

LoadError: ArgumentError: Package SomePackage not found in current path.
- Run `import Pkg; Pkg.add("SomePackage")` to install the SomePackage package.

You can try installing the package from the REPL using `] add SomePackage` or by using the Pkg package (which will not need to be added, as it comes with Julia already).

Some basic data types that any programming language has:

In [2]:
name = "Liam Doherty" # Strings
integer = 10 # Integer number
float = 2.7 # Floating Point number
integer_as_float = 1. # Integer value, stored as floating point (useful for type stability)

1.0

You can also suppress outputs with a semicolon:

In [3]:
variable = 4;

You can check a variable's type with `typeof`

In [4]:
typeof(integer_as_float)

Float64

Printing can be done with the `println` command:

In [5]:
println(name)
println(float)

Liam Doherty
2.7


We can also check a function's documentation (without searching online) with `?`:

In [6]:
? println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


It's straightforward to define a function (very MATLAB-esque)

In [ ]:
function function_name(input)
    # Do stuff to shift input to output
    output = input
    return output
end

You can also write inline functions (helpful for mathematical functions like $f(x) = x^2$):

In [7]:
f(x) = x^2
f(4)

16

You can also use keyword arguments or defaults in your functions:

In [8]:
function calculate_gravity_force(mass, g = 9.8; return_force = true)
    if return_force == true
        return mass*g
    else
        return -1.
    end
end

calculate_gravity_force (generic function with 2 methods)

In [9]:
calculate_gravity_force(10)

98.0

In [10]:
calculate_gravity_force(10, 1.6) # calculation for the Moon

16.0

In [11]:
calculate_gravity_force(10, return_force = false)

-1.0

Vectors and matrices are very common data structures among scientific codes:

In [12]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [13]:
V = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [14]:
VT = [1; 2; 3; 4] # Transpose of V, often we want column vectors. Also, notice that this is a vector, not a matrix!

4-element Vector{Int64}:
 1
 2
 3
 4

In [15]:
V' # We can also take the transpose directly with ', but again notice the type difference!

4×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3
 4

It's important to note that Julia uses 1-based indexing:

In [16]:
VT[1]

1

We can also slice matrices to obtain submatrices:

In [17]:
B = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [18]:
B[:, 3]

3-element Vector{Int64}:
 3
 6
 9

In [19]:
B[1:2, 2:end] # Notice the use of end here!

2×2 Matrix{Int64}:
 2  3
 5  6

Also, Julia is column major, not row major (Python is a row major language): Illustration:

In [20]:
for i = 1:length(B)
    print("$(B[i]) ")
end

1 4 7 2 5 8 3 6 9 

Now let's look at some examples of loops and control flow:

In [23]:
for i = 1:5
    print("$i ")
end

println() # Line break in output

j = 1
while j <= 5
    print("$j ")
    j += 1
end

println()

k = 10
if k > 50
    println("k is larger than 50!")
elseif k > 25
    println("k is greater than 25!")
else
    println("k is less than 25.")
end

1 2 3 4 5 
1 2 3 4 5 
k is less than 25.


Example usage of `continue` and `break`:

In [24]:
i = 1
while true
    if i < 10
        i += 1
        continue
    elseif i > 20
        break
    else
        println(i)
        i += 1
    end
end

10
11
12
13
14
15
16
17
18
19
20


The final (very important!) feature we will discuss is broadcasting. Take the function below and define an array:

In [25]:
function multiply_by_6(n::Int)
   return 6*n
end

multiply_by_6 (generic function with 1 method)

In [26]:
array = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [27]:
multiply_by_6(array)

LoadError: MethodError: no method matching multiply_by_6(::Matrix{Int64})
Closest candidates are:
  multiply_by_6(::Int64) at In[25]:1

We can't apply the function to the array, because it expects a single integer. But we can apply the function to the array elementwise by using the broadcasting feature with the dot operator `.`:

In [28]:
multiply_by_6.(array)

1×3 Matrix{Int64}:
 6  12  18

Alternatively, we can use the dot **macro**:

In [29]:
@. multiply_by_6(array)

1×3 Matrix{Int64}:
 6  12  18

This macro is very helpful when you have an expression where you need to have a lot of dot operators:

In [30]:
@. sin(2*cos(array)) # instead of sin.(2*cos.(array))

1×3 Matrix{Float64}:
 0.882243  -0.739477  -0.917444

Finally, some resources:

Documentation for useful packages:

Base Julia - https://docs.julialang.org/en/v1/

LinearAlgebra - https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

Plots - https://docs.juliaplots.org/stable/

StatsBase - https://juliastats.org/StatsBase.jl/stable/

DifferentialEquations - https://diffeq.sciml.ai/stable/

Other Resources:

Discourse: https://discourse.julialang.org/

Slack: https://julialang.org/slack/

Forem: https://forem.julialang.org/